### ISSUE TITLE
Escaping function

### ISSUE THREAD

**Issue by AudriusButkevicius** [gobwas/glob#1]
Ala QuoteMeta from regexp package, that handles c -> \c and so on.

**Comment by gobwas** [comment]
Got it. Will do it in few days =)

**Comment by gobwas** [comment]
Hi @AudriusButkevicius! Sorry for the huge delay, but better late, than never =)
I've done this func :fireworks:

**Comment by AudriusButkevicius** [comment]
Tyvm
