### ISSUE TITLE
Rejects commas

### ISSUE THREAD

**Issue by calmh** [gobwas/glob#11]
Parsing a pattern like `foo,bar.txt` fails with `syntax error: separator not inside terms list`. Obviously, this is intentional. However it would make more sense to me to accept this as a literal comma as that is a valid filename character and the lack of brackets does indicate a terms list was not intended here.

**Comment by gobwas** [comment]
Hi, @calmh! 
Looks like you are right. I will try to check this thing this week.
Thanks!

**Comment by gobwas** [comment]
Hi @calmh! Could you check current version? Just pushed changes into the master..

**Comment by calmh** [comment]
It passes my tests! :) Thank you!

**Comment by gobwas** [comment]
🍻
