### ISSUE TITLE
please tag and version this project

### ISSUE THREAD

**Issue by aviau** [gobwas/glob#14]
Hello,

Can you please tag and version this project?

I am the Debian Maintainer for glob and versioning would help Debian keep up with development.

**Comment by gobwas** [comment]
Hi! Yes, just thought about tag this lib by semver yesterday.
At now, I am refactoring lexer functionality, and after that – will tag the source.
Ok? =)

**Comment by aviau** [comment]
Thank you!

Please close this issue when you tag so that I am notified.

**Comment by gobwas** [comment]
Hi @aviau!
Finally Ive made it. =)

There are two tags now:
 + `0.1.0` which is the same as you have, except that lexer was reimplemented and few bugs was fixed.
 + `0.2.0` the current master with refactored and little bit optimized compilation stage.

Thanks!

**Comment by aviau** [comment]
I forgot to say thanks again, now that you have closed the issue :).

I have just uploaded 0.2.0 to Debian! Make sure you keep tagging as development continues! (see http://semver.org/)
