### ISSUE TITLE
some type mistake?

### ISSUE THREAD

**Issue by sleepdragon** [gobwas/glob#19]
Your code in compiler.go:

......
	for i, j := 0, treeLength-1; commonTotal < treeLength && j >= 0 && !(breakLeft && breakLeft); i, j = i+1, j-1 {
		treeLeft := tree.Children[i]
		treeRight := tree.Children[j]

		for k := 0; k < len(nodes) && !(breakLeft && breakLeft); k++ {
......

 breakLeft && breakLeft

**Comment by gobwas** [comment]
Hi @sleepdragon!
Thank you for the catch =)
Fixed.
