### ISSUE TITLE
Use in a pubsub lib?

### ISSUE THREAD

**Issue by nkev** [gobwas/glob#2]
Thanks for sharing this. I'm relatively new to Go, but I would like to try my hand at a simple pubsub library that uses your glob package. I'm thinking, each subscriber instance would store a compiled Glob containing the list of its subscriptions, like this:

```go
// Subscriber glob with pattern-alternatives list 
Subscriber.Subscriptions = glob.MustCompile("{core.*,plugins.categories.*}")
```

Does that sound right to you?

**Comment by gobwas** [comment]
Hi @nkev,
Yes, this sounds totally right for me =)
