### ISSUE TITLE
Usage examples on Directories/Files?

### ISSUE THREAD

**Issue by IkiM0no** [gobwas/glob#22]
Hi, thanks for this promising looking package. I see all the great stuff in the README for matching strings, but could you please provide a short example for doing actual directory/file pattern matching using his library?

**Comment by gobwas** [comment]
Hi! Thanks for the feedback. This package is intended to match strings with glob syntax – which is simpler and can be faster than regular expressions.
For directory/file pattern matching you could use one from standard library – [filepath](https://golang.org/pkg/path/filepath/#Glob) package. Or, by any reason, you could apply this package to every entry name in a filesystem manually.
