### ISSUE TITLE
Not correct matching with alternatives and separator

### ISSUE THREAD

**Issue by valichek** [gobwas/glob#23]
```
glob.MustCompile("{*.google.*,*.yandex.*}", '.').Match("www.google.com") // true, as expected
glob.MustCompile("{*.google.*,yandex.*}", '.').Match("www.google.com") // false, wrong!
```

**Comment by gobwas** [comment]
Hi! Thanks for the report and sorry for delay.
I've found the bug inside the matching logic. It is not so trivial, so fixit it will take some time. Hope will finish it this week. Sorry.

**Comment by gobwas** [comment]
Hi @valichek fixed this for now. Sorry for such a long reaction. Thank you for the catch.
