### ISSUE TITLE
wildcard in curly brackets

### ISSUE THREAD

**Issue by Rikkuru** [gobwas/glob#28]
seems like wildcard in curly brackets  does not work. or only works if there is nothing after curly brackets?
`package main
import "github.com/gobwas/glob"

import "fmt"
func main() {
g := glob.MustCompile("{a*,b}c", '.')
fmt.Println(g.Match("abc")) // false expect true
}`

**Comment by gobwas** [comment]
Hi @Rikkuru, could you check it against `feature/v0.3` branch? It seems that this bug is already fixed.

**Comment by Rikkuru** [comment]
yes it is fixed in feature/v0.3
When will it be in master?

**Comment by gobwas** [comment]
Hey there. Sorry for so huge delay – finally I have refactored feature/v0.3 and it looks stable and passing tests. Could you please again check your case against it and I will merge it tomorrow, I hope.

**Comment by Rikkuru** [comment]
Hi @gobwas !
I checked it again, works fine in feature/v0.3
