### ISSUE TITLE
Asterisk at beginning matches like double-asterisk

### ISSUE THREAD

**Issue by kamermans** [gobwas/glob#29]
Thanks for the library, great work!

Please consider this example:
```go
g := glob.MustCompile("*.github.com")
fmt.Println(g.Match("api.github.com"))     // true
fmt.Println(g.Match("foo.api.github.com")) // true, but should be false

g = glob.MustCompile("**.github.com")
fmt.Println(g.Match("api.github.com"))     // true
fmt.Println(g.Match("foo.api.github.com")) // true
```

In my understanding (and use case), `*.github.com` should not match `foo.api.github.com` since the single asterisk should only match one component in the domain (`api`).  If I wanted to match multiple components, like `foo.api`, I would use `**.github.com`.

**Comment by calmh** [comment]
(Not package author, just interested bystander.)

You didn’t set the component delimiter, which is by default a slash (for file paths).

**Comment by kamermans** [comment]
Good point @calmh, but all the examples [and tests](https://github.com/gobwas/glob/blob/master/glob_test.go) assume the separator is `.`.  Do you know how I can set the separator?
