### ISSUE TITLE
Case insensitive match?

### ISSUE THREAD

**Issue by asmaloney** [gobwas/glob#37]
I asked in the [lefthook project](https://github.com/Arkweid/lefthook/issues/68#issuecomment-522484862) about case insensitivity and was pointed here.

Is it possible to do a case insensitive match?

**Comment by calmh** [comment]
It's easy to case fold / lowercase the pattern and match string before matching.

**Comment by asmaloney** [comment]
Ah, ok. So it's not supported in the match string somehow - it would require code changes to lefthook.

Thanks!
