### ISSUE TITLE
LICENSE file

### ISSUE THREAD

**Issue by client9** [gobwas/glob#6]
Hello,

Thanks for such a great library.  I hesitate to ask but could you add a LICENSE file to help clear up any (future) problems?

Ideally something from.. https://opensource.org/licenses  but hey it's your code!

thanks again

nickg

**Comment by gobwas** [comment]
Hi @client9! Thanks for the feedback, I've applied the MIT-License =)
:beers:

**Comment by client9** [comment]
thank you @gobwas !!
