### ISSUE TITLE
Is there any case when glob.Compile returns an error?

### ISSUE THREAD

**Issue by iav0207** [gobwas/glob#63]
I'm writing tests for my code using `glob` package and can't find any pattern that wouldn't compile. I was looking at the test cases in this repository and didn't find any error cases either.

So my question is: is there any input to `glob.Compile` that would yield an error?

I tried inputs with unbalanced brackets (`[` and `{`), they did compile as well.

**Comment by antialiasis** [comment]
I don't know if you're still looking for this a year later, but I happen to be here because GLOB patterns designed for SQLite are not compiling with glob.Compile - character classes containing a range as well as individual characters, like [0-9.], return an error on compile.

**Comment by iav0207** [comment]
Indeed, as I've just verified, the pattern like you provided, i.e., `[0-9.]`, won't compile. Closing this issue then. Thanks!
